version: '3.8'
services:
  awlog-server:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FLASK_ENV=production
      - TZ=Europe/Istanbul
